### ISSUE TITLE
Got an unexpected result

### ISSUE THREAD

**Issue by dlutwy** [Jinjiarui/GraphHINGE#2]
I downloaded the ml-100k(MovieLens 100K Dataset) and did the experiments with default args ( 3 epochs), however, the results I got are much higher than those reported in the paper.

Test AUC 0.9506 |  ACC 0.8792 | Test F1 0.8764 

I am wondering whether it is caused by my data processing scripts or other reason.

**Comment by Jinjiarui** [comment]
Thanks for your question. The reason is that the results here are reported in our previous KDD paper. In this repository, we actually show the implementation of our TOIS paper, which is the extended version. You can refer to the paper (https://arxiv.org/pdf/2011.12683.pdf) here.
