### ISSUE TITLE
sampling path but without omitting existing edge

### ISSUE THREAD

**Issue by dlutwy** [Jinjiarui/GraphHINGE#3]
Imho, omitting 20% of existing edges should be done before constructing the graph when doing 5 fold cross-validation.
Otherwise, meta-path sampling will generate a lot of paths involved with positive instances in the test&eval dataset, which is an information leak and should be unseen.

**Comment by Jinjiarui** [comment]
Thanks for your interest in our code. This code is from our previous version, not including all the data pre-processing code. We will update this repository after obtaining permission from the company. You can easily imply "remove edges" APIs from DGL to do this. Thanks a lot.
