### ISSUE TITLE
请教一下有关movielens数据集预处理的相关问题

### ISSUE THREAD

**Issue by zhj123169** [Jinjiarui/GraphHINGE#5]
感谢您在HIN领域作出的贡献！
我在运行您的代码dataloader.py 的 _load_movielens(self)时，想知道您运行时导入的
`_data_list = ['movie_genre.dat', 'user_occupation.dat', 'user_age.dat', 'user_movie.dat']`
四个文件是如何通过原始数据预处理得到的
对于其中的movie_genre.dat
`_movie, _genre = int(_line[0]), int(_line[1])`
是如何将类型变为数字的呢？
如果您能为我解答或者将您处理后并且实际测试的movielens数据集提供给我，我将感激不尽，谢谢！

**Comment by Jinjiarui** [comment]
Thanks for your interest in our paper. The raw data is available at https://github.com/librahu/HIN-Datasets-for-Recommendation-and-Network-Embedding. You can find exact these four files (i.e., 'movie_genre.dat', 'user_occupation.dat', 'user_age.dat', 'user_movie.dat') in the open-sourced Github repository.
