### ISSUE TITLE
experiments results in KDD paper and "GraphHINGE: Learning Interaction Models of Structured Neighborhood on Heterogeneous Information Network"

### ISSUE THREAD

**Issue by zhj123169** [Jinjiarui/GraphHINGE#6]
您好，感谢您在HIN领域出色的工作！
  我了解了您在KDD 2020的paper以及后面这篇paper中与KDDpaper中方法相似的部分，以`GraphHINGE_FFT.py`中的方法为例，kDD论文中movielens的acc为0.7896，后一篇为0.8837，我看主要方法部分没有很明显的区别（仅指在这个py文件中所涉及的网络结构），而且baseline的相同方法也有一定程度的提升，请问这种提升是因为什么呢？是因为hyperparameter的设置，数据的预处理方式，还是因为一些两篇论文细节方面我没有充分进行理解，在细节上是有区别的（仅指在KDD论文中提到的方法)？
  我是这个方向的初学者，如果您能对我的疑惑进行解答，我将非常感谢！

**Comment by Jinjiarui** [comment]
Thanks a lot for your interest. There are a couple of differences between the implementations of these versions. The first one is that we use negative sampling techniques for all the baselines and our methods, which largely influences their performance. Hence, we re-conduct experiments and fine-tune the hyper-parameters in this case. The second one is that we re-write the convolution operations. The implementations of KDD version are implemented by ourselves, which are naturally less effective and efficient than the official ones with lots of additional optimizations. Therefore, there is a big difference. And we highly recommend other researchers try the latest version, namely TOIS version.
