### ISSUE TITLE
About Potential Data Leakage

### ISSUE THREAD

**Issue by aHuiWang** [Jinjiarui/GraphHINGE#7]
I noticed that you used all “user-item” edges to construct the heterogeneous graph. And based on it, you then predict the user-item edges (i.e. recommendation). Would this cause data leakage?

**Comment by Jinjiarui** [comment]
Good question. One solution is to remove all "user-item" edges in the test data in the heterogeneous graph. It's easy to try.

**Comment by aHuiWang** [comment]
OK. Good solution.
